<?php  

$ACTION_HOME_INITIAL="HOME_INITIAL";
$ACTION_LOGIN="LOGIN_SUBMIT";
$ACTION_SIGN_UP="SIGN_UP_SUBMIT";


$EDIT_USER="EDIT_USER";
$EDIT_USER_ADDRESS="EDIT_USER_ADDRESS";
$EDIT_USER_PASSWORD="EDIT_USER_PASSWORD";


$SIGN_OUT="SIGN_OUT";
$ADD_NEW_PRODUCT="ADD_NEW_PRODUCT";
$EDIT_PRODUCT="EDIT_PRODUCT";
$GET_PRODUCT="GET_PRODUCT";
$GET_ORDER="GET_ORDER";


$CART_ADD_PRODUCT="CART_ADD_PRODUCT";
$CART_DELETE_PRODUCT="CART_DELETE_PRODUCT";
$CART_UPDATE_PRODUCT="CART_UPDATE_PRODUCT";


$CHECKOUT_CART="CHECKOUT_CART";
$RESOVE_CONFLICT_CART="RESOVE_CONFLICT_CART"

?>