<?php  

$ACTION_HOME_INITIAL="HOME_INITIAL";
$ACTION_LOGIN="LOGIN_SUBMIT";
$ACTION_SIGN_UP="SIGN_UP_SUBMIT";

$SIGN_OUT="SIGN_OUT";
$ADD_NEW_PRODUCT="ADD_NEW_PRODUCT";


$CART_ADD_PRODUCT="CART_ADD_PRODUCT";
$CART_DELETE_PRODUCT="CART_DELETE_PRODUCT";
$CART_UPDATE_PRODUCT="CART_UPDATE_PRODUCT";


$CHECKOUT_CART="CHECKOUT_CART";
$RESOVE_CONFLICT_CART="RESOVE_CONFLICT_CART"

?>