<?php
// Url
$NOT_FOUND_URL="/404Page";
$HOME="/home";

// Constant
$CURRENT_USER_INFO="CURRENT_USER_INFO";
$LOGIN_SUCCESS="Login successfully";
$LOGIN_FAILED="Wrong email or password";
$LOGIN_EMAIL="email";
$LOGIN_PASSWORD="password";

$SIGN_UP_EMAIL="signup_email";
$SIGN_UP_PASSWORD="signup_password";

$DEL_FLAG_VALID=0;
$DEL_FLAG_INVALID=1;


$CART_STATUS_PENDING=0;

$ORDER_STATUS_PENDING=0;
$ORDER_STATUS_SUCCEED=1;


// Admin tab
$ADD_PRODUCT="ADD_PRODUCT";
$LIST_PRODUCT="LIST_PRODUCT";
$EDIT_PRODUCT="EDIT_PRODUCT";
$DELETE_PRODUCT="DELETE_PRODUCT";
$LIST_ODER="LIST_ODER";
$ADD_USER="ADD_USER";
$EDIT_USER="EDIT_USER";
$STATISTICAL="STATISTICAL";

// 
$PERMISSION_USER=0;
$PERMISSION_ADMIN=1;


$ORDER_STATUS_PENDING=0;
$ORDER_STATUS_REJECT=-1;
$ORDER_STATUS_FULFILLED=1;


?>